# Generated by Django 4.2.23 on 2025-06-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('discount_price', models.FloatField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('product_description', models.TextField(max_length=255)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
